(function(g){var window=this;'use strict';var QJa=function(a,b){return g.Pb(a,b)},x4=function(a,b,c){a.l.set(b,c)},y4=function(a){x4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Va()).toString(36));
return a},z4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.l,b,c)},RJa=function(a,b){var c=[];
g.$i(b,function(d){try{var e=g.Sn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Rn(e)&&c.push(d)},a);
return c},SJa=function(a,b){b=RJa(a,b);
g.Db(b,function(c){g.Sn.prototype.remove.call(this,c)},a)},TJa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},UJa=function(a,b){g.jb(a,b)||a.push(b)},A4=function(a){var b=0,c;
for(c in a)b++;return b},VJa=function(a,b){b=b instanceof g.Ec?b:g.Lc(b,/^data:image\//i.test(b));
a.src=g.Gc(b)},WJa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},XJa=function(a){if(a.Ag&&"function"==typeof a.Ag)return a.Ag();
if("string"===typeof a)return a.split("");if(g.Pa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Mb(a)},YJa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Pa(a)||"string"===typeof a)g.Db(a,b,void 0);else{if(a.wh&&"function"==typeof a.wh)var c=a.wh();else if(a.Ag&&"function"==typeof a.Ag)c=void 0;else if(g.Pa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Nb(a);d=XJa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},ZJa=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.J=d);return e},B4=function(){},C4=function(a,b){g.Jq[a]=!0;
var c=g.Hq();c&&c.publish.apply(c,arguments);g.Jq[a]=!1},D4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$Ja(this,a.capabilities||""),aKa(this,a.experiments||""))},$Ja=function(a,b){a.capabilities.clear();
g.Le(b.split(","),g.Ta(QJa,bKa)).forEach(function(c){a.capabilities.add(c)})},aKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},E4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},F4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},dKa=function(a){return new E4(a)},eKa=function(a){return Array.isArray(a)?g.Qc(a,dKa):[]},G4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},H4=function(a){return Array.isArray(a)?"["+g.Qc(a,G4).join(",")+"]":"null"},I4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},fKa=function(a){return g.Qc(a,function(b){return{key:b.id,
name:b.name}})},J4=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},K4=function(a,b){return g.fb(a,function(c){return F4(c,b)})},gKa=function(){var a=(0,g.Qu)();
a&&SJa(a,a.i.rk(!0))},L4=function(){var a=g.Tu("yt-remote-connected-devices")||[];
g.zb(a);return a},hKa=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qc(a,function(d,e){return 0==e?d:d.substring(c.length)})},iKa=function(a){g.Su("yt-remote-connected-devices",a,86400)},N4=function(){if(M4)return M4;
var a=g.Tu("yt-remote-device-id");a||(a=I4(),g.Su("yt-remote-device-id",a,31536E3));for(var b=L4(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return M4=d},O4=function(){var a=L4(),b=N4();
g.jb(a,b);g.Wu()&&g.Cb(a,b);a=hKa(a);if(g.kb(a))try{g.xo("remote_sid")}catch(c){}else try{g.vo("remote_sid",a.join(","),-1)}catch(c){}},jKa=function(){return g.Tu("yt-remote-session-browser-channel")},kKa=function(){return g.Tu("yt-remote-local-screens")||[]},lKa=function(){g.Su("yt-remote-lounge-token-expiration",!0,86400)},mKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qc(kKa(),function(d){return d.loungeToken}),c=g.Qc(a,function(d){return d.loungeToken});
g.fh(c,function(d){return!g.jb(b,d)})&&lKa();
g.Su("yt-remote-local-screens",a,31536E3)},nKa=function(a,b){g.Su("yt-remote-session-browser-channel",a);
g.Su("yt-remote-session-screen-id",b);a=L4();b=N4();g.jb(a,b)||a.push(b);iKa(a);O4()},P4=function(a){a||(g.Vu("yt-remote-session-screen-id"),g.Vu("yt-remote-session-video-id"));
O4();a=L4();g.ob(a,N4());iKa(a)},oKa=function(){if(!Q4){var a=g.bo();
a&&(Q4=new g.Mn(a))}},pKa=function(){oKa();
return Q4?!!Q4.get("yt-remote-use-staging-server"):!1},R4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},qKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},rKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},S4=function(a){a.length?sKa(a.shift(),function(){S4(a)}):T4()},tKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},sKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.kd(d,g.hg(a));(document.head||document.documentElement).appendChild(d)},uKa=function(){var a=R4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},T4=function(){var a=rKa();
a&&a(!1,"No cast extension found")},U4=function(){if(vKa){var a=2,b=rKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;sKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",T4,c)}},wKa=function(){U4();
var a=uKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");S4(a)},yKa=function(){U4();
var a=uKa();a.push.apply(a,g.la(xKa.map(tKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");S4(a)},V4=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Ff=b;this.C=(0,g.C)(this.ML,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},W4=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Ff=b;this.u=null;this.i=!1;this.l=0;this.yb=null},X4=function(a){a.yb=g.Mm(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,X4(a))},a.Ff);
var b=a.u;a.u=null;a.B.apply(null,b)},Y4=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return WJa(a)},Z4=function(){},$4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},b5=function(a){a5.dispatchEvent(new zKa(a5,a))},zKa=function(a,b){g.Il.call(this,"statevent",a);
this.stat=b},c5=function(){},AKa=function(){},CKa=function(a){return(a=BKa(a))?new ActiveXObject(a):new XMLHttpRequest},BKa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},d5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.K_(this);this.u=new g.Lm;this.u.setInterval(250)},EKa=function(a,b,c){a.Pq=1;
a.Dl=y4(b.clone());a.Io=c;a.G=!0;DKa(a,null)},e5=function(a,b,c,d,e){a.Pq=1;
a.Dl=y4(b.clone());a.Io=null;a.G=c;e&&(a.UI=!1);DKa(a,d)},DKa=function(a,b){a.Gq=Date.now();
f5(a);a.Fm=a.Dl.clone();z4(a.Fm,"t",a.J);a.pu=0;a.He=a.i.yz(a.i.Ot()?b:null);0<a.Dy&&(a.Sw=new W4((0,g.C)(a.KJ,a,a.He),a.Dy));a.B.Na(a.He,"readystatechange",a.ZR);b=a.Rm?g.Wb(a.Rm):{};a.Io?(a.Gx="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.He.send(a.Fm,a.Gx,a.Io,b)):(a.Gx="GET",a.UI&&!g.Be&&(b.Connection="close"),a.He.send(a.Fm,a.Gx,null,b));a.i.Gi(1)},HKa=function(a,b,c){for(var d=!0;!a.zn&&a.pu<c.length;){var e=FKa(a,c);
if(e==g5){4==b&&(a.yl=4,b5(15),d=!1);break}else if(e==GKa){a.yl=4;b5(16);d=!1;break}else h5(a,e)}4==b&&0==c.length&&(a.yl=1,b5(17),d=!1);a.Qi=a.Qi&&d;d||(i5(a),j5(a))},FKa=function(a,b){var c=a.pu,d=b.indexOf("\n",c);
if(-1==d)return g5;c=Number(b.substring(c,d));if(isNaN(c))return GKa;d+=1;if(d+c>b.length)return g5;b=b.substr(d,c);a.pu=d+c;return b},JKa=function(a,b){a.Gq=Date.now();
f5(a);var c=b?window.location.hostname:"";a.Fm=a.Dl.clone();x4(a.Fm,"DOMAIN",c);x4(a.Fm,"t",a.J);try{a.Ti=new ActiveXObject("htmlfile")}catch(m){i5(a);a.yl=7;b5(22);j5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in k5)f=k5[f];else if(f in IKa)f=k5[f]=IKa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
k5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.hd(g.ic("b/12014412"),d+"</body></html>");a.Ti.open();a.Ti.write(g.dd(c));a.Ti.close();a.Ti.parentWindow.m=(0,g.C)(a.xR,a);a.Ti.parentWindow.d=(0,g.C)(a.gI,a,!0);a.Ti.parentWindow.rpcClose=(0,g.C)(a.gI,a,!1);c=a.Ti.createElement("DIV");a.Ti.parentWindow.document.body.appendChild(c);d=g.Kc(a.Fm.toString());d=g.pd(g.Gc(d));d=g.hd(g.ic("b/12014412"),'<iframe src="'+d+'"></iframe>');g.id(c,d);a.i.Gi(1)},f5=function(a){a.KC=Date.now()+
a.C;
KKa(a,a.C)},KKa=function(a,b){if(null!=a.Uq)throw Error("WatchDog timer not null");
a.Uq=$4((0,g.C)(a.FR,a),b)},l5=function(a){a.Uq&&(g.A.clearTimeout(a.Uq),a.Uq=null)},j5=function(a){a.i.KD()||a.zn||a.i.Gu(a)},i5=function(a){l5(a);
g.Ci(a.Sw);a.Sw=null;a.u.stop();g.BEa(a.B);if(a.He){var b=a.He;a.He=null;b.abort();b.dispose()}a.Ti&&(a.Ti=null)},h5=function(a,b){try{a.i.YH(a,b),a.i.Gi(4)}catch(c){}},MKa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;LKa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){MKa(a,b,c,d,f)},f)})}},LKa=function(a,b,c){var d=new Image;
d.onload=function(){try{m5(d),c(!0)}catch(e){}};
d.onerror=function(){try{m5(d),c(!1)}catch(e){}};
d.onabort=function(){try{m5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{m5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
VJa(d,a)},m5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},n5=function(a){g.bm.call(this);
this.headers=new g.Om;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.Ba=this.L=this.xa=!1;this.J=0;this.X=null;this.Ka="";this.Y=this.Ea=!1},NKa=function(a){return g.ze&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},OKa=function(a){return"content-type"==a.toLowerCase()},QKa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;PKa(a);o5(a)},PKa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},SKa=function(a){if(a.B&&"undefined"!=typeof g.O_)if(a.ma[1]&&4==p5(a)&&2==a.getStatus())q5(a,"Local request error detected and ignored");
else if(a.L&&4==p5(a))g.Mm(a.VH,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){q5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.zd(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!RKa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<p5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";PKa(a)}}finally{o5(a)}}},o5=function(a,b){if(a.i){TKa(a);
var c=a.i,d=a.ma[0]?g.Ma:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},TKa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},p5=function(a){return a.i?a.i.readyState:0},r5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},q5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},UKa=function(a){this.i=a;
this.l=new Z4},VKa=function(a){var b=s5(a.i,a.Kr,"/mail/images/cleardot.gif");
y4(b);MKa(b.toString(),5E3,(0,g.C)(a.HM,a),3,2E3);a.Gi(1)},u5=function(a){var b=a.i.L;
if(null!=b)b5(5),b?(b5(11),t5(a.i,a,!1)):(b5(12),t5(a.i,a,!0));else if(a.Jg=new d5(a,void 0,void 0,void 0),a.Jg.Rm=a.Ey,b=a.i,b=s5(b,b.Ot()?a.zr:null,a.Fy),b5(5),!g.ze||g.ce(10))z4(b,"TYPE","xmlhttp"),e5(a.Jg,b,!1,a.zr,!1);else{z4(b,"TYPE","html");var c=a.Jg;a=!!a.zr;c.Pq=3;c.Dl=y4(b.clone());JKa(c,a)}},v5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new Z4;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},WKa=function(a,b){this.i=a;
this.map=b;this.context=null},XKa=function(a,b,c,d){g.Il.call(this,"timingevent",a);
this.size=b;this.Ht=d},YKa=function(a){g.Il.call(this,"serverreachability",a)},aLa=function(a){ZKa(a);
if(3==a.eb){var b=a.Ys++,c=a.ov.clone();x4(c,"SID",a.l);x4(c,"RID",b);x4(c,"TYPE","terminate");w5(a,c);b=new d5(a,a.l,b,void 0);b.Pq=2;b.Dl=y4(c.clone());VJa(new Image,b.Dl.toString());b.Gq=Date.now();f5(b)}$Ka(a)},bLa=function(a){a.cN(1,0);
a.ov=s5(a,null,a.Gy);x5(a)},ZKa=function(a){a.Hl&&(a.Hl.abort(),a.Hl=null);
a.Td&&(a.Td.cancel(),a.Td=null);a.wk&&(g.A.clearTimeout(a.wk),a.wk=null);y5(a);a.yg&&(a.yg.cancel(),a.yg=null);a.Ol&&(g.A.clearTimeout(a.Ol),a.Ol=null)},cLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new WKa(a.yO++,b));2!=a.eb&&3!=a.eb||x5(a)},dLa=function(a){var b=0;
a.Td&&b++;a.yg&&b++;return b},x5=function(a){a.yg||a.Ol||(a.Ol=$4((0,g.C)(a.eI,a),0),a.Xp=0)},fLa=function(a,b){if(1==a.eb){if(!b){a.Ys=Math.floor(1E5*Math.random());
b=a.Ys++;var c=new d5(a,"",b,void 0);c.Rm=a.mj;var d=z5(a),e=a.ov.clone();x4(e,"RID",b);x4(e,"CVER","1");w5(a,e);EKa(c,e,d);a.yg=c;a.eb=2}}else 3==a.eb&&(b?eLa(a,b):0==a.i.length||a.yg||eLa(a))},eLa=function(a,b){if(b)if(6<a.An){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Ys-1;b=z5(a)}else c=b.L,b=b.Io;else c=a.Ys++,b=z5(a);var d=a.ov.clone();x4(d,"SID",a.l);x4(d,"RID",c);x4(d,"AID",a.rq);w5(a,d);c=new d5(a,a.l,c,a.Xp+1);c.Rm=a.mj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yg=c;EKa(c,d,b)},w5=function(a,b){a.yf&&(a=a.yf.FF())&&g.Fb(a,function(c,d){x4(b,d,c)})},z5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.An&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={hp:e.hp},f++){e.hp=a.i[f].i;var h=a.i[f].map;e.hp=6>=a.An?f:e.hp-d;try{g.Fb(h,function(l){return function(m,n){c.push("req"+l.hp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.hp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},gLa=function(a){a.Td||a.wk||(a.G=1,a.wk=$4((0,g.C)(a.dI,a),0),a.Kp=0)},A5=function(a){if(a.Td||a.wk||3<=a.Kp)return!1;
a.G++;a.wk=$4((0,g.C)(a.dI,a),hLa(a,a.Kp));a.Kp++;return!0},t5=function(a,b,c){a.Ex=c;
a.nj=b.ek;a.C||bLa(a)},y5=function(a){null!=a.Hn&&(g.A.clearTimeout(a.Hn),a.Hn=null)},hLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},B5=function(a,b){if(2==b||9==b){var c=null;
a.yf&&(c=null);var d=(0,g.C)(a.CS,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),y4(c));LKa(c.toString(),1E4,d)}else b5(2);iLa(a,b)},iLa=function(a,b){a.eb=0;
a.yf&&a.yf.WE(b);$Ka(a);ZKa(a)},$Ka=function(a){a.eb=0;
a.nj=-1;if(a.yf)if(0==a.u.length&&0==a.i.length)a.yf.iz();else{g.rb(a.u);var b=g.rb(a.i);a.u.length=0;a.i.length=0;a.yf.iz(b)}},s5=function(a,b,c){var d=g.Zm(c);
if(""!=d.i)b&&g.Tm(d,b+"."+d.i),g.Um(d,d.u);else{var e=window.location;d=ZJa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ds&&g.Fb(a.ds,function(f,h){x4(d,h,f)});
x4(d,"VER",a.An);w5(a,d);return d},jLa=function(){},kLa=function(){this.i=[];
this.l=[]},lLa=function(a,b){this.action=a;
this.params=b||{}},C5=function(a,b){g.F.call(this);
this.i=new g.J(this.pR,0,this);g.H(this,this.i);this.Ff=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},D5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Ln;this.l=new C5(this.jS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},mLa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Ex,sessionId:a.i.l,arrayId:a.i.rq}},nLa=function(a,b){a.L=b||0;
a.l.stop();E5(a);a.i&&(3==a.i.getState()&&fLa(a.i),aLa(a.i));a.L=0},F5=function(a){return!!a.i&&3==a.i.getState()},E5=function(a){if(a.i){var b=a.Y(),c=a.i.mj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.mj=c}},G5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.zd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ad(a)||"";a=g.Xc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.l=!1))},H5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Md(c+b,{})},I5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.B,d,!0),onError:g.Ta(a.u,e),onTimeout:g.Ta(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mp(b,a)},rLa=function(){var a=oLa;
pLa();J5.push(a);qLa()},K5=function(a,b){pLa();
var c=sLa(a,String(b));g.kb(J5)?tLa(c):(qLa(),g.Db(J5,function(d){d(c)}))},pLa=function(){J5||(J5=g.La("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",J5,void 0))},tLa=function(a){var b=(L5+1)%50;
L5=b;M5[b]=a;N5||(N5=49==b)},qLa=function(){var a=J5;
if(M5[0]){var b=N5?L5:-1;do{b=(b+1)%50;var c=M5[b];g.Db(a,function(d){d(c)})}while(b!=L5);
M5=Array(50);L5=-1;N5=!1}},sLa=function(a,b){var c=(Date.now()-uLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O5=function(a){g.O.call(this);
this.G=a;this.screens=[]},vLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},wLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Le(a.screens,function(f){return!!J4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=vLa(a,b[d])||c;return c},xLa=function(a,b){var c=a.screens.length;
a.screens=g.Le(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},P5=function(a,b,c,d,e){g.O.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},R5=function(a){O5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;Q5(this);this.info("Initializing with "+H4(this.screens))},yLa=function(a){if(a.screens.length){var b=g.Qc(a.screens,function(d){return d.id}),c=H5(a.l,"/pairing/get_lounge_token_batch");
I5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.zN,a),(0,g.C)(a.yN,a))}},Q5=function(a){if(g.Go("deprecate_pair_servlet_enabled"))return wLa(a,[]);
var b=eKa(kKa());b=g.Le(b,function(c){return!c.uuid});
return wLa(a,b)},S5=function(a,b){mKa(g.Qc(a.screens,cKa));
b&&lKa()},U5=function(a,b){g.O.call(this);
this.G=b;b=(b=g.Tu("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.jb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;T5("Initialized with "+g.Cj(this.i))},V5=function(a,b,c){var d=H5(a.C,"/pairing/get_screen_availability");
I5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},W5=function(a,b){a:if(A4(b)!=A4(a.i))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(T5("Updated online screens: "+g.Cj(a.i)),a.i=b,a.W("screenChange"));zLa(a)},X5=function(a){isNaN(a.u)||g.hp(a.u);
a.u=g.fp((0,g.C)(a.JB,a),0<a.B&&a.B<g.Va()?2E4:1E4)},T5=function(a){K5("OnlineScreenService",a)},ALa=function(a){var b={};
g.Db(a.G(),function(c){c.token?b[c.token]=c.id:this.Hd("Requesting availability of screen w/o lounge token.")});
return b},zLa=function(a){a=g.Nb(g.Gb(a.i,function(b){return b}));
g.zb(a);a.length?g.Su("yt-remote-online-screen-ids",a.join(","),60):g.Vu("yt-remote-online-screen-ids")},Y5=function(a,b){b=void 0===b?!1:b;
O5.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};BLa(this)},DLa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Ug(),l=c?K4(h,c):null;c&&(a.J||l)||(l=K4(h,b));if(l){l.uuid=b;var m=Z5(a,l);V5(a.i,m,function(n){e(n?m:null)})}else c?CLa(a,c,(0,g.C)(function(n){var p=Z5(this,new E4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));V5(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},ELa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},FLa=function(a,b,c){V5(a.i,b,c)},CLa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mp(H5(a.B,"/pairing/get_lounge_token_batch"),e)},GLa=function(a){a.screens=a.l.Ug();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+H4(a.screens))},BLa=function(a){$5(a);
a.l=new R5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.FN,a));GLa(a);a.J||(a.u=eKa(g.Tu("yt-remote-automatic-screen-cache")||[]));$5(a);a.info("Initializing automatic screens: "+H4(a.u));a.i=new U5(a.B,(0,g.C)(a.Ug,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},Z5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=K4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||HLa(a));$5(a);a.C[b.uuid]=b.id;g.Su("yt-remote-device-id-map",a.C,31536E3);return b},HLa=function(a){a=g.Le(a.u,function(b){return"shortLived"!=b.idType});
g.Su("yt-remote-automatic-screen-cache",g.Qc(a,cKa))},$5=function(a){a.C=g.Tu("yt-remote-device-id-map")||{}},a6=function(a,b,c){g.O.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},b6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},ILa=function(a,b){a.B&&(a.B.token=b,Z5(a.u,a.B));
a.W("sessionScreen",a.B)},c6=function(a,b){K5(a.xa,b)},d6=function(a,b,c){a6.call(this,a,b,"CastSession");
var d=this;this.Ba=c;this.l=null;this.Y=(0,g.C)(this.RL,this);this.ra=(0,g.C)(this.JR,this);this.X=g.fp(function(){JLa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},e6=function(a,b){g.hp(a.J);
a.J=0;0==b?KLa(a):a.J=g.fp(function(){KLa(a)},b)},KLa=function(a){LLa(a,"getLoungeToken");
g.hp(a.C);a.C=g.fp(function(){MLa(a,null)},3E4)},LLa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Cj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ma,(0,g.C)(function(){c6(this,"Failed to send message: "+b+".")},a)):c6(a,"Sending yt message without session: "+g.Cj(c))},f6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.UF(b,function(c){b6(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},OLa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new E4(b);NLa(a,d,function(e){e?(a.ma=!0,Z5(a.u,d),b6(a,d),a.V="unknown",e6(a,c)):(g.Lo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},JLa=function(a,b){g.hp(a.X);
a.X=0;b?a.Ba.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?OLa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Lo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),f6(a,b.screenId))):(g.Lo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
f6(a,b.screenId)):f6(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},MLa=function(a,b){g.hp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,e6(a,3E4)):(ILa(a,b.loungeToken),a.ma=!1,a.V="unknown",e6(a,b.loungeTokenRefreshIntervalMs))},NLa=function(a,b,c,d){g.hp(a.G);
a.G=0;FLa(a.u,b,function(e){e||0>d?c(e):a.G=g.fp(function(){NLa(a,b,c,d-1)},300)})},PLa=function(a){g.hp(a.L);
a.L=0;g.hp(a.G);a.G=0;g.hp(a.X);a.X=0;g.hp(a.C);a.C=0;g.hp(a.J);a.J=0},g6=function(a,b,c,d){a6.call(this,a,b,"DialSession");
this.Ea=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ca=null;this.X=g.Ma;this.V=NaN;this.Ba=(0,g.C)(this.SL,this);this.C=g.Ma;this.J=this.G=0;this.Y=!1;this.ma="unknown"},h6=function(a){var b;
return!!(a.Ea.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},QLa=function(a){a.C=a.u.MD(a.ra,a.i.label,a.i.friendlyName,h6(a),function(b,c){a.C=g.Ma;
a.Y=!0;b6(a,b);"shortLived"==b.idType&&0<c&&i6(a,c)},function(b){a.C=g.Ma;
a.Zf(b)})},RLa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;pKa()&&(b.env_useStageMdx=1);return g.Jd(b)},j6=function(a){return new Promise(function(b){a.ra=I4();
if(a.Ca){var c=new chrome.cast.DialLaunchResponse(!0,RLa(a));b(c);QLa(a)}else a.X=function(){g.hp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,RLa(a));b(d);QLa(a)},a.V=g.fp(function(){a.X()},100)})},TLa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new E4(b);return(new Promise(function(e){SLa(a,d,function(f){f?(a.Y=!0,Z5(a.u,d),b6(a,d),i6(a,c)):g.Lo(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):j6(a)})},ULa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){DLa(a.u,c,b,d,function(f){f&&f.token&&b6(a,f);e(f)},function(f){c6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):j6(a)})},SLa=function(a,b,c,d){g.hp(a.G);
a.G=0;FLa(a.u,b,function(e){e||0>d?c(e):a.G=g.fp(function(){SLa(a,b,c,d-1)},300)})},i6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
h6(a)&&(g.hp(a.J),a.J=0,0==b?VLa(a):a.J=g.fp(function(){VLa(a)},b))},VLa=function(a){h6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,i6(a,3E4)):(a.Y=!1,a.ma="unknown",ILa(a,b.loungeToken),i6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";i6(a,3E4)})},WLa=function(a){g.hp(a.G);
a.G=0;g.hp(a.J);a.J=0;a.C();a.C=function(){};
g.hp(a.V)},k6=function(a,b){a6.call(this,a,b,"ManualSession");
this.l=g.fp((0,g.C)(this.tq,this,null),150)},l6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.C)(this.EQ,this)},XLa=function(a,b){return b?g.fb(a.u,function(c){return F4(b,c.label)},a):null},m6=function(a){K5("Controller",a)},oLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},n6=function(a){return a.J||!!a.u.length||!!a.i},o6=function(a,b,c){b!=a.i&&(g.Ci(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.bI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.tq(null)):a.W("yt-remote-cast2-session-change",null))},YLa=function(a){var b=a.l.LD(),c=a.i&&a.i.i;
a=g.Qc(b,function(d){c&&F4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=XLa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cMa=function(a,b,c,d){d.disableCastApi?p6("Cannot initialize because disabled by Mdx config."):ZLa()?$La(b,d)&&(q6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?aMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?aMa(a,c):(r6("Failed to load cast API: "+f),s6(!1),q6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),
bMa(),c(!1))},d.loadCastApiSetupScript?g.Xu("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=R4()&&wKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?T4():89<=R4()?yKa():(U4(),S4(xKa.map(tKa))))):p6("Cannot initialize because not running Chrome")},bMa=function(){p6("dispose");
var a=t6();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);dMa(!1);g.Mq(u6);u6.length=0},v6=function(){return!!g.Tu("yt-remote-cast-installed")},eMa=function(){var a=g.Tu("yt-remote-cast-receiver");
return a?a.friendlyName:null},fMa=function(){p6("clearCurrentReceiver");
g.Vu("yt-remote-cast-receiver")},gMa=function(){return v6()?t6()?t6().getCastSession():(r6("getCastSelector: Cast is not initialized."),null):(r6("getCastSelector: Cast API is not installed!"),null)},x6=function(){v6()?t6()?w6()?(p6("Requesting cast selector."),t6().requestSession()):(p6("Wait for cast API to be ready to request the session."),u6.push(g.Lq("yt-remote-cast2-api-ready",x6))):r6("requestCastSelector: Cast is not initialized."):r6("requestCastSelector: Cast API is not installed!")},y6=
function(a,b){w6()?t6().setConnectedScreenStatus(a,b):r6("setConnectedScreenStatus called before ready.")},ZLa=function(){var a=0<=g.Xc.search(/ (CrMo|Chrome|CriOS)\//);
return g.RA||a},hMa=function(a,b){t6().init(a,b)},$La=function(a,b){var c=!1;
t6()||(a=new l6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Su("yt-remote-cast-available",d);C4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){p6("onReceiverSelected: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);C4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){p6("onReceiverResumed: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);C4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){p6("onSessionChange: "+G4(d));
d||g.Vu("yt-remote-cast-receiver");C4("yt-remote-cast2-session-change",d)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
p6("cloudview.createSingleton_: "+c);return c},t6=function(){return g.La("yt.mdx.remote.cloudview.instance_")},aMa=function(a,b){s6(!0);
q6(!1);hMa(a,function(c){c?(dMa(!0),g.Nq("yt-remote-cast2-api-ready")):(r6("Failed to initialize cast API."),s6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),bMa());b(c)})},p6=function(a){K5("cloudview",a)},r6=function(a){K5("cloudview",a)},s6=function(a){p6("setCastInstalled_ "+a);
g.Su("yt-remote-cast-installed",a)},w6=function(){return!!g.La("yt.mdx.remote.cloudview.apiReady_")},dMa=function(a){p6("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},q6=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},z6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Cj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},A6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Cj=!1;a.hasNext=!1;a.J=0;a.G=g.Va();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},B6=function(a){return a.lc()?(g.Va()-a.G)/1E3:0},C6=function(a,b){a.J=b;
a.G=g.Va()},D6=function(a){switch(a.playerState){case 1:case 1081:return(g.Va()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},E6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&A6(a)},F6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Xb(a.trackData);b.hasPrevious=a.Cj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},H6=function(a,b){g.O.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new kLa;this.l=this.i=null;this.L=(0,g.C)(this.gP,this);this.G=(0,g.C)(this.gt,this);this.J=(0,g.C)(this.fP,this);this.V=(0,g.C)(this.nP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.VB,this),iMa(this))):c=3;0!=c&&(b?this.VB(c):g.fp((0,g.C)(function(){this.VB(c)},this),0));
(a=gMa())&&G6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},I6=function(a){return new z6(a.u.getPlayerContextData())},iMa=function(a){g.Db("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Ta(this.BQ,b),this))},a)},jMa=function(a){g.Db(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},J6=function(a){return 1==a.getState()},K6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},M6=function(a,b,c){var d=I6(a);
C6(d,c);-1E3!=d.playerState&&(d.playerState=b);L6(a,d)},N6=function(a,b,c){a.u.sendMessage(b,c)},L6=function(a,b){jMa(a);
a.u.setPlayerContextData(F6(b));iMa(a)},G6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.gt(null));
a.l=b;a.l&&(K5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.gt(a.l.media[0]))},kMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=I6(a);b.contentId!=d.videoId&&K5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;C6(d,a.i.getEstimatedTime());L6(a,d)}else K5("CP","No cast media video. Ignoring state update.")},O6=function(a,b,c){return(0,g.C)(function(d){this.Hd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hd("Retrying "+b+" using MDx browser channel."),N6(this,b,c))},a)},P6=function(a,b,c){g.O.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.ac=this.i=null;this.xa=a;this.V.push(g.Lp(window,"beforeunload",(0,g.C)(this.vN,this)));this.l=[];this.ac=new z6;this.Ba=b.id;this.ra=b.idType;this.i=lMa(this,c);this.i.subscribe("handlerOpened",this.kP,this);this.i.subscribe("handlerClosed",this.hP,this);this.i.subscribe("handlerError",this.iP,this);this.i.subscribe("handlerMessage",this.jP,this);this.i.fx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.ac.videoId;g.Wu()&&g.Su("yt-remote-session-video-id",d)},this)},Q6=function(a){K5("conn",a)},lMa=function(a,b){return new D5(H5(a.xa,"/bc"),b,!1,function(){return a.QD()},"shortLived"==a.ra)},R6=function(a,b){a.W("proxyStateChange",b)},mMa=function(a){a.C=g.fp((0,g.C)(function(){Q6("Connecting timeout");
this.Tp(1)},a),2E4)},S6=function(a){g.hp(a.C);
a.C=NaN},T6=function(a){g.hp(a.Y);
a.Y=NaN},nMa=function(a){U6(a);
a.X=g.fp((0,g.C)(function(){V6(this,"getNowPlaying")},a),2E4)},U6=function(a){g.hp(a.X);
a.X=NaN},pMa=function(a,b){b&&(S6(a),T6(a));
var c=F5(a.i)&&isNaN(a.C);b==c?b&&(R6(a,1),V6(a,"getSubtitlesTrack")):b?(a.TF()&&a.ac.reset(),R6(a,1),V6(a,"getNowPlaying"),oMa(a)):a.Tp(1)},qMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ac.videoId&&(g.Sb(b.params)?a.ac.trackData=null:a.ac.trackData=b.params,a.W("remotePlayerChange"))},rMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ac.listId=b.params.listId||a.ac.listId;E6(a.ac,c,d);a.W("remoteQueueChange")},tMa=function(a,b){b.params=b.params||{};
rMa(a,b);sMa(a,b);a.W("autoplayDismissed")},sMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
C6(a.ac,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ac.playerState&&(c=-1E3);a.ac.playerState=c;c=Number(b.params.loadedTime);a.ac.L=isNaN(c)?0:c;c=Number(b.params.duration);a.ac.C=isNaN(c)?0:c;c=a.ac;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.ac;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.ac.playerState?nMa(a):U6(a);a.W("remotePlayerChange")},uMa=function(a,b){if(-1E3!=a.ac.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ac.playerState=c;b=parseInt(b.params.currentTime,10);C6(a.ac,isNaN(b)?0:b);a.W("remotePlayerChange")}},vMa=function(a,b){var c="true"==b.params.muted;
a.ac.volume=parseInt(b.params.volume,10);a.ac.muted=c;a.W("remotePlayerChange")},wMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},xMa=function(a,b){var c="true"==b.params.hasNext;
a.ac.Cj="true"==b.params.hasPrevious;a.ac.hasNext=c;a.W("previousNextChange")},oMa=function(a){g.hp(a.L);
a.L=g.fp((0,g.C)(a.Tp,a,1),864E5)},V6=function(a,b,c){c?Q6("Sending: action="+b+", params="+g.Cj(c)):Q6("Sending: action="+b);
a.i.sendMessage(b,c)},W6=function(a){O5.call(this,"ScreenServiceProxy");
this.Ef=a;this.i=[];this.i.push(this.Ef.$_s("screenChange",(0,g.C)(this.WL,this)));this.i.push(this.Ef.$_s("onlineScreenChange",(0,g.C)(this.iQ,this)))},BMa=function(a,b){oKa();
if(!Q4||!Q4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;gKa();O4();X6||(X6=new G5(b?b.loungeApiHost:void 0),pKa()&&(X6.i="/api/loungedev"));Y6||(Y6=g.La("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",Y6,void 0));yMa();var c=Z6();if(!c){var d=new Y5(X6,b?b.disableAutomaticScreenCache||!1:!1);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=Z6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});cMa(a,d,function(f){f?$6()&&y6($6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){C4("yt-remote-receiver-availability-change")})},e)}b&&!g.La("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),a7("Initializing: "+g.Cj(b)),b7.push(g.Lq("yt-remote-cast2-availability-change",function(){C4("yt-remote-receiver-availability-change")})),b7.push(g.Lq("yt-remote-cast2-receiver-selected",
function(){c7(null);
C4("yt-remote-auto-connect","cast-selector-receiver")})),b7.push(g.Lq("yt-remote-cast2-receiver-resumed",function(){C4("yt-remote-receiver-resumed","cast-selector-receiver")})),b7.push(g.Lq("yt-remote-cast2-session-change",zMa)),b7.push(g.Lq("yt-remote-connection-change",function(f){f?y6($6(),"YouTube TV"):d7()||(y6(null,null),fMa())})),a=e7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Go("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),a7(" -- with channel params: "+g.Cj(a)),a?(g.Su("yt-remote-session-app",a.app),g.Su("yt-remote-session-name",a.name)):(g.Vu("yt-remote-session-app"),g.Vu("yt-remote-session-name")),g.Ha("yt.mdx.remote.channelParams_",a,void 0),c.start(),$6()||AMa())}},CMa=function(){var a=Z6().Ef.$_gos();
var b=f7();b&&g7()&&(J4(a,b)||a.push(b));return fKa(a)},h7=function(){var a=DMa();
!a&&v6()&&eMa()&&(a={key:"cast-selector-receiver",name:eMa()});return a},DMa=function(){var a=CMa(),b=f7();
b||(b=d7());return g.fb(a,function(c){return b&&F4(b,c.key)?!0:!1})},f7=function(){var a=$6();
if(!a)return null;var b=Z6().Ug();return K4(b,a)},zMa=function(a){a7("remote.onCastSessionChange_: "+G4(a));
if(a){var b=f7();if(b&&b.id==a.id){if(y6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))i7&&(i7.token=a),(b=g7())&&b.fx(a)}else b&&j7(),k7(a,1)}else g7()&&j7()},j7=function(){w6()?t6().stopSession():r6("stopSession called before API ready.");
var a=g7();a&&(a.disconnect(1),l7(null))},m7=function(){var a=g7();
return!!a&&3!=a.getProxyState()},a7=function(a){K5("remote",a)},Z6=function(){if(!n7){var a=g.La("yt.mdx.remote.screenService_");
n7=a?new W6(a):null}return n7},$6=function(){return g.La("yt.mdx.remote.currentScreenId_")},EMa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},FMa=function(){return g.La("yt.mdx.remote.connectData_")},c7=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},g7=function(){return g.La("yt.mdx.remote.connection_")},l7=function(a){var b=g7();
c7(null);a||EMa("");g.Ha("yt.mdx.remote.connection_",a,void 0);Y6&&(g.Db(Y6,function(c){c(a)}),Y6.length=0);
b&&!a?C4("yt-remote-connection-change",!1):!b&&a&&C4("yt-remote-connection-change",!0)},d7=function(){var a=g.Wu();
if(!a)return null;var b=Z6();if(!b)return null;b=b.Ug();return K4(b,a)},k7=function(a,b){$6();
f7()&&f7();o7?i7=a:(EMa(a.id),a=new P6(X6,a,e7()),a.connect(b,FMa()),a.subscribe("beforeDisconnect",function(c){C4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){g7()&&(g7(),l7(null))}),a.subscribe("browserChannelAuthError",function(){var c=f7();
c&&"shortLived"==c.idType&&(w6()?t6().handleBrowserChannelAuthError():r6("refreshLoungeToken called before API ready."))}),l7(a))},AMa=function(){var a=d7();
a?(a7("Resume connection to: "+G4(a)),k7(a,0)):(P4(),fMa(),a7("Skipping connecting because no session screen found."))},yMa=function(){var a=e7();
if(g.Sb(a)){a=N4();var b=g.Tu("yt-remote-session-name")||"",c=g.Tu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},e7=function(){return g.La("yt.mdx.remote.channelParams_")||{}},p7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Qb=c;this.events=new g.SL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){GMa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.TI(64);this.i=new g.J(this.cJ,500,this);this.u=new g.J(this.dJ,1E3,this);this.L=new V4(this.US,0,this);this.B={};this.V=new g.J(this.DJ,1E3,this);this.J=new W4(this.seekTo,1E3,this);this.Y=g.Ma;g.H(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.RP);this.events.N(b,"captionschanged",this.dP);this.events.N(b,"captionssettingschanged",this.iJ);this.events.N(b,"videoplayerreset",this.Lw);this.events.N(b,"mdxautoplaycancel",function(){d.Qb.pF()});
a=this.Qb;a.Ga();a.subscribe("proxyStateChange",this.XH,this);a.subscribe("remotePlayerChange",this.qt,this);a.subscribe("remoteQueueChange",this.Lw,this);a.subscribe("previousNextChange",this.UH,this);a.subscribe("nowAutoplaying",this.OH,this);a.subscribe("autoplayDismissed",this.lH,this);g.H(this,this.i);g.H(this,this.u);g.H(this,this.L);g.H(this,this.V);g.H(this,this.J);this.iJ();this.Lw();this.qt()},GMa=function(a,b){if(q7(a)){a.Qb.unsubscribe("remotePlayerChange",a.qt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=I6(a.Qb);if(c!==d.volume||b!==d.muted)a.Qb.setVolume(c,b),a.V.start();a.Qb.subscribe("remotePlayerChange",a.qt,a)}},HMa=function(a){a.Tb(0);
a.i.stop();a.Hb(new g.TI(64))},r7=function(a,b){if(q7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Zb(c,b));a.Qb.PD(a.I.getVideoData(1).videoId,c);a.B=I6(a.Qb).trackData}},s7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Qb.playVideo(c.videoId,b,d,e,c.playerParams,c.xa,TJa(c));a.Hb(new g.TI(1))},IMa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{lG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},q7=function(a){return I6(a.Qb).videoId===a.I.getVideoData(1).videoId},t7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.zK(this,250);this.learnMoreButton=
this.Aa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Aa("ytp-mdx-manual-pairing-popup-ok");g.H(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},u7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Da:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.zK(this,250);this.cancelButton=this.Aa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Aa("ytp-mdx-privacy-popup-confirm");g.H(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},v7=function(a){g.W.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.wma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.zK(this,250);g.H(this,this.i);this.N(a,"presentingplayerstatechange",this.l);JMa(this,a.qb())},JMa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.V(b,128)?g.wH("Error on $RECEIVER_NAME",c):b.lc()||g.V(b,4)?g.wH("Playing on $RECEIVER_NAME",c):g.wH("Connected to $RECEIVER_NAME",c);a.Oa("statustext",b);a.i.show()}else a.i.hide()},w7=function(a,b){g.LO.call(this,"Play on",0,a,b);
this.I=a;this.Cm={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},x7=function(a){g.$L.call(this,a);
this.Di={key:I4(),name:"This computer"};this.nh=null;this.subscriptions=[];this.xB=this.Qb=null;this.Cm=[this.Di];this.Jl=this.Di;this.Yc=new g.TI(64);this.GG=0;this.Oe=-1;this.xq=null;this.xt=this.lw=!1;this.Go=this.Eq=null;if(!g.fD(this.player.T())&&!g.gD(this.player.T())){a=this.player;var b=g.FL(a);b&&(b=b.Xl())&&(b=new w7(a,b),g.H(this,b));b=new v7(a);g.H(this,b);g.PL(a,b.element,4);this.Eq=new u7;g.H(this,this.Eq);g.PL(a,this.Eq.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.xq=new t7,g.H(this,this.xq),g.PL(a,this.xq.element,4));this.xt=!!d7();this.lw=!!g.Tu("yt-remote-manual-pairing-warning-shown")}},y7=function(a){a.Go&&(a.player.removeEventListener("presentingplayerstatechange",a.Go),a.Go=null)},KMa=function(a,b,c){a.Yc=c;
a.player.W("presentingplayerstatechange",new g.fH(c,b))},LMa=function(a,b,c){var d=!1;
1===b?d=!a.xt:2===b&&(d=!a.lw);d&&g.hH(c,8)&&(a.player.pauseVideo(),y7(a))},z7=function(a,b){if(b.key!==a.Jl.key)if(b.key===a.Di.key)j7();
else{if(a.xq&&!a.lw&&b!==a.Di&&"cast-selector-receiver"!==b.key&&g.BD(a.player.T()))MMa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.xt||!a.Eq);(c?0:g.BD(a.player.T())||g.FD(a.player.T()))&&NMa(a)}a.Jl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.xa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=TJa(c))&&(a.locationInfo=c)}a7("Connecting to: "+g.Cj(b));"cast-selector-receiver"==b.key?(c7(a||null),b=a||null,
w6()?t6().setLaunchParams(b):r6("setLaunchParams called before ready.")):!a&&m7()&&$6()==b.key?C4("yt-remote-connection-change",!0):(j7(),c7(a||null),a=Z6().Ug(),(b=K4(a,b.key))&&k7(b,1))}},NMa=function(a){a.player.qb().lc()?a.player.pauseVideo():(a.Go=function(b){LMa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Go));
a.Eq&&a.Eq.Pc();g7()||(o7=!0)},MMa=function(a){a.player.qb().lc()?a.player.pauseVideo():(a.Go=function(b){LMa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Go));
a.xq&&a.xq.Pc();g7()||(o7=!0)},IKa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},k5={"'":"\\'"},OMa={},bKa={RT:"atp",w3:"ska",m2:"que",x0:"mus",v3:"sus",LX:"dsp",H2:"seq",X_:"mic",MW:"dpa",gU:"cds"},Q4,M4="",vKa=qKa("loadCastFramework")||qKa("loadCastApplicationFramework"),xKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Wa(V4,g.F);g.k=V4.prototype;g.k.xg=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Va()+this.Ff:this.yb=g.Mm(this.C,this.Ff)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();V4.Gd.va.call(this)};
g.k.ML=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Mm(this.C,this.u-g.Va()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(W4,g.F);g.k=W4.prototype;g.k.xg=function(a){this.u=arguments;this.yb||this.l?this.i=!0:X4(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,X4(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};Z4.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
Z4.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var a5=new g.bm;g.v(zKa,g.Il);c5.prototype.i=null;c5.prototype.getOptions=function(){var a;(a=this.i)||(a={},BKa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var A7;g.Wa(AKa,c5);A7=new AKa;g.k=d5.prototype;g.k.Rm=null;g.k.Qi=!1;g.k.Uq=null;g.k.KC=null;g.k.Gq=null;g.k.Pq=null;g.k.Dl=null;g.k.Fm=null;g.k.Io=null;g.k.He=null;g.k.pu=0;g.k.Ti=null;g.k.Gx=null;g.k.yl=null;g.k.yr=-1;g.k.UI=!0;g.k.zn=!1;g.k.Dy=0;g.k.Sw=null;var GKa={},g5={};g.k=d5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.ZR=function(a){a=a.target;var b=this.Sw;b&&3==p5(a)?b.xg():this.KJ(a)};
g.k.KJ=function(a){try{if(a==this.He)a:{var b=p5(this.He),c=this.He.G,d=this.He.getStatus();if(g.ze&&!g.ce(10)||g.Be&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.mg&&!r5(this.He))break a;this.zn||4!=b||7==c||(8==c||0>=d?this.i.Gi(3):this.i.Gi(2));l5(this);var e=this.He.getStatus();this.yr=e;var f=r5(this.He);(this.Qi=200==e)?(4==b&&i5(this),this.G?(HKa(this,b,f),g.mg&&this.Qi&&3==b&&(this.B.Na(this.u,"tick",this.UR),this.u.start())):h5(this,f),this.Qi&&!this.zn&&(4==b?this.i.Gu(this):(this.Qi=
!1,f5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.yl=3,b5(13)):(this.yl=0,b5(14)),i5(this),j5(this))}}catch(h){this.He&&r5(this.He)}finally{}};
g.k.UR=function(){var a=p5(this.He),b=r5(this.He);this.pu<b.length&&(l5(this),HKa(this,a,b),this.Qi&&4!=a&&f5(this))};
g.k.xR=function(a){$4((0,g.C)(this.wR,this,a),0)};
g.k.wR=function(a){this.zn||(l5(this),h5(this,a),f5(this))};
g.k.gI=function(a){$4((0,g.C)(this.vR,this,a),0)};
g.k.vR=function(a){this.zn||(i5(this),this.Qi=a,this.i.Gu(this),this.i.Gi(4))};
g.k.cancel=function(){this.zn=!0;i5(this)};
g.k.FR=function(){this.Uq=null;var a=Date.now();0<=a-this.KC?(2!=this.Pq&&this.i.Gi(3),i5(this),this.yl=2,b5(18),j5(this)):KKa(this,this.KC-a)};
g.k.getLastError=function(){return this.yl};g.Wa(n5,g.bm);var RKa=/^https?$/i,PMa=["POST","PUT"];g.k=n5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?CKa(this.ra):CKa(A7);this.ma=this.ra?this.ra.getOptions():A7.getOptions();this.i.onreadystatechange=(0,g.C)(this.VH,this);try{B4(q5(this,"Opening Xhr")),this.Ba=!0,this.i.open(b,String(a),!0),this.Ba=!1}catch(f){B4(q5(this,"Error opening Xhr: "+f.message));QKa(this,f);return}a=
c||"";var e=this.headers.clone();d&&YJa(d,function(f,h){e.set(h,f)});
d=g.fb(e.wh(),OKa);c=g.A.FormData&&a instanceof g.A.FormData;!g.jb(PMa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ka&&(this.i.responseType=this.Ka);"withCredentials"in this.i&&this.i.withCredentials!==this.Ea&&(this.i.withCredentials=this.Ea);try{TKa(this),0<this.J&&(this.Y=NKa(this.i),B4(q5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.JD,this)):this.X=g.Mm(this.JD,this.J,this)),B4(q5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){B4(q5(this,"Send error: "+f.message)),QKa(this,f)}};
g.k.JD=function(){"undefined"!=typeof g.O_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,q5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(q5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),o5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),o5(this,!0));n5.Gd.va.call(this)};
g.k.VH=function(){this.Ga()||(this.Ba||this.L||this.C?SKa(this):this.DQ())};
g.k.DQ=function(){SKa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==p5(this)};
g.k.getStatus=function(){try{return 2<p5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=UKa.prototype;g.k.Ey=null;g.k.Jg=null;g.k.Tw=!1;g.k.eJ=null;g.k.hv=null;g.k.LA=null;g.k.Fy=null;g.k.eb=null;g.k.ek=-1;g.k.zr=null;g.k.Kr=null;g.k.connect=function(a){this.Fy=a;a=s5(this.i,null,this.Fy);b5(3);this.eJ=Date.now();var b=this.i.J;null!=b?(this.zr=b[0],(this.Kr=b[1])?(this.eb=1,VKa(this)):(this.eb=2,u5(this))):(z4(a,"MODE","init"),this.Jg=new d5(this,void 0,void 0,void 0),this.Jg.Rm=this.Ey,e5(this.Jg,a,!1,null,!0),this.eb=0)};
g.k.HM=function(a){if(a)this.eb=2,u5(this);else{b5(4);var b=this.i;b.nj=b.Hl.ek;B5(b,9)}a&&this.Gi(2)};
g.k.yz=function(a){return this.i.yz(a)};
g.k.abort=function(){this.Jg&&(this.Jg.cancel(),this.Jg=null);this.ek=-1};
g.k.KD=function(){return!1};
g.k.YH=function(a,b){this.ek=a.yr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.nj=this.ek;B5(a,2);return}this.zr=c[0];this.Kr=c[1]}else a=this.i,a.nj=this.ek,B5(a,2);else if(2==this.eb)if(this.Tw)b5(7),this.LA=Date.now();else if("11111"==b){if(b5(6),this.Tw=!0,this.hv=Date.now(),a=this.hv-this.eJ,!g.ze||g.ce(10)||500>a)this.ek=200,this.Jg.cancel(),b5(12),t5(this.i,this,!0)}else b5(8),this.hv=this.LA=Date.now(),this.Tw=!1};
g.k.Gu=function(){this.ek=this.Jg.yr;if(this.Jg.Qi)0==this.eb?this.Kr?(this.eb=1,VKa(this)):(this.eb=2,u5(this)):2==this.eb&&((!g.ze||g.ce(10)?!this.Tw:200>this.LA-this.hv)?(b5(11),t5(this.i,this,!1)):(b5(12),t5(this.i,this,!0)));else{0==this.eb?b5(9):2==this.eb&&b5(10);var a=this.i;this.Jg.getLastError();a.nj=this.ek;B5(a,2)}};
g.k.Ot=function(){return this.i.Ot()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Gi=function(a){this.i.Gi(a)};g.k=v5.prototype;g.k.mj=null;g.k.ds=null;g.k.yg=null;g.k.Td=null;g.k.Gy=null;g.k.ov=null;g.k.LE=null;g.k.Hu=null;g.k.Ys=0;g.k.yO=0;g.k.yf=null;g.k.Ol=null;g.k.wk=null;g.k.Hn=null;g.k.Hl=null;g.k.Ex=null;g.k.rq=-1;g.k.FG=-1;g.k.nj=-1;g.k.Xp=0;g.k.Kp=0;g.k.An=8;g.Wa(XKa,g.Il);g.Wa(YKa,g.Il);g.k=v5.prototype;g.k.connect=function(a,b,c,d,e){b5(0);this.Gy=b;this.ds=c||{};d&&void 0!==e&&(this.ds.OSID=d,this.ds.OAID=e);this.C?($4((0,g.C)(this.cF,this,a),100),bLa(this)):this.cF(a)};
g.k.cF=function(a){this.Hl=new UKa(this);this.Hl.Ey=this.mj;this.Hl.l=this.B;this.Hl.connect(a)};
g.k.KD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.eI=function(a){this.Ol=null;fLa(this,a)};
g.k.dI=function(){this.wk=null;this.Td=new d5(this,this.l,"rpc",this.G);this.Td.Rm=this.mj;this.Td.Dy=0;var a=this.LE.clone();x4(a,"RID","rpc");x4(a,"SID",this.l);x4(a,"CI",this.Ex?"0":"1");x4(a,"AID",this.rq);w5(this,a);if(!g.ze||g.ce(10))x4(a,"TYPE","xmlhttp"),e5(this.Td,a,!0,this.Hu,!1);else{x4(a,"TYPE","html");var b=this.Td,c=!!this.Hu;b.Pq=3;b.Dl=y4(a.clone());JKa(b,c)}};
g.k.YH=function(a,b){if(0!=this.eb&&(this.Td==a||this.yg==a))if(this.nj=a.yr,this.yg==a&&3==this.eb)if(7<this.An){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.wk){if(this.Td)if(this.Td.Gq+3E3<this.yg.Gq)y5(this),this.Td.cancel(),this.Td=null;else break a;A5(this);b5(19)}}else this.FG=a[1],0<this.FG-this.rq&&37500>a[2]&&this.Ex&&0==this.Kp&&!this.Hn&&(this.Hn=$4((0,g.C)(this.aP,this),6E3));else B5(this,11)}else b!=OMa.zW.i&&B5(this,11);else if(this.Td==
a&&y5(this),!g.rc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.rq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Hu=c[2],c=c[3],null!=c?this.An=c:this.An=6,this.eb=3,this.yf&&this.yf.YE(),this.LE=s5(this,this.Ot()?this.Hu:null,this.Gy),gLa(this)):"stop"==c[0]&&B5(this,7):3==this.eb&&("stop"==c[0]?B5(this,7):"noop"!=c[0]&&this.yf&&this.yf.XE(c),this.Kp=0)};
g.k.aP=function(){null!=this.Hn&&(this.Hn=null,this.Td.cancel(),this.Td=null,A5(this),b5(20))};
g.k.Gu=function(a){if(this.Td==a){y5(this);this.Td=null;var b=2}else if(this.yg==a)this.yg=null,b=1;else return;this.nj=a.yr;if(0!=this.eb)if(a.Qi)1==b?(b=a5,b.dispatchEvent(new XKa(b,a.Io?a.Io.length:0,Date.now()-a.Gq,this.Xp)),x5(this),this.u.length=0):gLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.nj)){if(d=1==b)this.yg||this.Ol||1==this.eb||2<=this.Xp?d=!1:(this.Ol=$4((0,g.C)(this.eI,this,a),hLa(this,this.Xp)),this.Xp++,d=!0);d=!(d||2==b&&A5(this))}if(d)switch(c){case 1:B5(this,
5);break;case 4:B5(this,10);break;case 3:B5(this,6);break;case 7:B5(this,12);break;default:B5(this,2)}}};
g.k.cN=function(a){if(!g.jb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.CS=function(a){a?b5(2):(b5(1),iLa(this,8))};
g.k.yz=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new n5;a.Ea=!1;return a};
g.k.isActive=function(){return!!this.yf&&this.yf.isActive(this)};
g.k.Gi=function(a){var b=a5;b.dispatchEvent(new YKa(b,a))};
g.k.Ot=function(){return!(!g.ze||g.ce(10))};
g.k=jLa.prototype;g.k.YE=function(){};
g.k.XE=function(){};
g.k.WE=function(){};
g.k.iz=function(){};
g.k.FF=function(){return{}};
g.k.isActive=function(){return!0};g.k=kLa.prototype;g.k.isEmpty=function(){return g.kb(this.i)&&g.kb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.jb(this.i,a)||g.jb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.GEa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.l,a)};
g.k.Ag=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Wa(C5,g.F);g.k=C5.prototype;g.k.pR=function(){this.Ff=Math.min(3E5,2*this.Ff);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Ff+15E3*Math.random();g.mn(this.i,a);this.l=g.Va()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Ff=5E3};g.Wa(D5,jLa);g.k=D5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Ci(this.u),nLa(this),g.Ci(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ga=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new v5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.yf=null);d.yf=this;this.i=d;E5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.mj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.mj=f}e?(3!=e.getState()&&0==dLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.rq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Zb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):F5(this)&&(E5(this),cLa(this.i,a))};
g.k.YE=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)cLa(this.i,a[b])}this.W("handlerOpened")};
g.k.WE=function(a){var b=2==a&&401==this.i.nj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.iz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.FF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Zb(a,this.C);return a};
g.k.XE=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),aLa(this.i)):this.W("handlerMessage",new lLa(a[0],a[1]))};
g.k.fx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.mj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.mj=b}};
g.k.jS=function(){this.l.isActive();0==dLa(this.i)&&this.connect(this.C,this.B)};G5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
G5.prototype.C=function(a){a(Error("request timed out"))};var uLa=Date.now(),J5=null,M5=Array(50),L5=-1,N5=!1;g.Wa(O5,g.O);O5.prototype.Ug=function(){return this.screens};
O5.prototype.contains=function(a){return!!J4(this.screens,a)};
O5.prototype.get=function(a){return a?K4(this.screens,a):null};
O5.prototype.info=function(a){K5(this.G,a)};g.v(P5,g.O);g.k=P5.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.oI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.hp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.O.prototype.va.call(this)};
g.k.oI=function(){this.yb=NaN;this.i=g.mp(H5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.OL,this),onError:(0,g.C)(this.NL,this),onTimeout:(0,g.C)(this.PL,this)})};
g.k.OL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new E4(a),b)};
g.k.NL=function(a){this.i=null;a.status&&404==a.status?this.l>=QMa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=QMa[this.l],this.yb=g.fp((0,g.C)(this.oI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.PL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var QMa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Wa(R5,O5);g.k=R5.prototype;g.k.start=function(){Q5(this)&&this.W("screenChange");!g.Tu("yt-remote-lounge-token-expiration")&&yLa(this);g.hp(this.i);this.i=g.fp((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){Q5(this);vLa(this,a);S5(this,!1);this.W("screenChange");b(a);a.token||yLa(this)};
g.k.remove=function(a,b){var c=Q5(this);xLa(this,a)&&(S5(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Cx=function(a,b,c,d){var e=Q5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.hp(this.i);R5.Gd.va.call(this)};
g.k.zN=function(a){Q5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S5(this,!b);b&&K5(this.G,"Missed "+b+" lounge tokens.")};
g.k.yN=function(a){K5(this.G,"Requesting lounge tokens failed: "+a)};g.v(U5,g.O);g.k=U5.prototype;g.k.start=function(){var a=parseInt(g.Tu("yt-remote-fast-check-period")||"0",10);(this.B=g.Va()-144E5<a?0:a)?X5(this):(this.B=g.Va()+3E5,g.Su("yt-remote-fast-check-period",this.B),this.JB())};
g.k.isEmpty=function(){return g.Sb(this.i)};
g.k.update=function(){T5("Updating availability on schedule.");var a=this.G(),b=g.Gb(this.i,function(c,d){return c&&!!K4(a,d)},this);
W5(this,b)};
g.k.va=function(){g.hp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.va.call(this)};
g.k.JB=function(){g.hp(this.u);this.u=NaN;this.l&&this.l.abort();var a=ALa(this);if(A4(a)){var b=H5(this.C,"/pairing/get_screen_availability");this.l=I5(this.C,b,{lounge_token:g.Nb(a).join(",")},(0,g.C)(this.YQ,this,a),(0,g.C)(this.XQ,this))}else W5(this,{}),X5(this)};
g.k.YQ=function(a,b){this.l=null;var c=g.Nb(ALa(this));if(g.Bb(c,g.Nb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;W5(this,c);X5(this)}else this.Hd("Changing Screen set during request."),this.JB()};
g.k.XQ=function(a){this.Hd("Screen availability failed: "+a);this.l=null;X5(this)};
g.k.Hd=function(a){K5("OnlineScreenService",a)};g.Wa(Y5,O5);g.k=Y5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Cx=function(a,b,c,d){this.l.contains(a)?this.l.Cx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K5(this.G,a),d(Error(a)))};
g.k.Ug=function(a){return a?this.screens:g.qb(this.screens,g.Le(this.u,function(b){return!this.contains(b)},this))};
g.k.LD=function(){return g.Le(this.Ug(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.MD=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new P5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Ci(l);e(Z5(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Ci(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.QL=function(a,b,c,d){g.mp(H5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new E4(f.screen||{});if(!e.name||ELa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);ELa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(Z5(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Ci(this.l);g.Ci(this.i);Y5.Gd.va.call(this)};
g.k.FN=function(){GLa(this);this.W("screenChange");this.i.update()};
Y5.prototype.dispose=Y5.prototype.dispose;g.Wa(a6,g.O);g.k=a6.prototype;g.k.getScreen=function(){return this.B};
g.k.Zf=function(a){this.Ga()||(a&&c6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){K5(this.xa,a)};
g.k.ND=function(){return null};
g.k.TB=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){c6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.TB("");a6.Gd.va.call(this)};g.v(d6,a6);g.k=d6.prototype;g.k.SB=function(a){if(this.l){if(this.l==a)return;c6(this,"Overriding cast session with new session object");PLa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);LLa(this,"getMdxSessionStatus")};
g.k.tq=function(a){this.info("launchWithParams no-op for Cast: "+g.Cj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.Zf()},this),(0,g.C)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.TB=function(){};
g.k.va=function(){this.info("disposeInternal");PLa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;a6.prototype.va.call(this)};
g.k.JR=function(a,b){if(!this.Ga())if(b)if(b=Y4(b),g.Qa(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Cj(b)),a){case "mdxSessionStatus":JLa(this,b);break;case "loungeToken":MLa(this,b);break;default:c6(this,"Unknown youtube message: "+a)}else c6(this,"Unable to parse message.");else c6(this,"No data in message.")};
g.k.UF=function(a,b,c,d){g.hp(this.L);this.L=0;DLa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(c6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.fp((0,g.C)(this.UF,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.ND=function(){return this.l};
g.k.RL=function(a){this.Ga()||a||(c6(this,"Cast session died."),this.Zf())};g.v(g6,a6);g.k=g6.prototype;g.k.SB=function(a){this.l=a;this.l.addUpdateListener(this.Ba)};
g.k.tq=function(a){this.Ca=a;this.X()};
g.k.stop=function(){WLa(this);this.l?this.l.stop((0,g.C)(this.Zf,this,null),(0,g.C)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.va=function(){WLa(this);this.l&&this.l.removeUpdateListener(this.Ba);this.l=null;a6.prototype.va.call(this)};
g.k.SL=function(a){this.Ga()||a||(c6(this,"DIAL session died."),this.C(),this.C=g.Ma,this.Zf())};g.v(k6,a6);k6.prototype.stop=function(){this.Zf()};
k6.prototype.SB=function(){};
k6.prototype.tq=function(){g.hp(this.l);this.l=NaN;var a=K4(this.u.Ug(),this.i.label);a?b6(this,a):this.Zf(Error("No such screen"))};
k6.prototype.va=function(){g.hp(this.l);this.l=NaN;a6.prototype.va.call(this)};g.v(l6,g.O);g.k=l6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.IQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.ZH,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.uP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ga()||
(chrome.cast.addReceiverActionListener(this.G),rLa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.OD,this)),this.u=YLa(this),chrome.cast.setCustomReceivers(this.u,g.Ma,(0,g.C)(function(f){this.Hd("Failed to set initial custom receivers: "+g.Cj(f))},this)),this.W("yt-remote-cast2-availability-change",n6(this)),b(!0))},this),(0,g.C)(function(f){this.Hd("Failed to initialize API: "+g.Cj(f));
b(!1)},this))};
g.k.oS=function(a,b){m6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)m6("Unsetting old screen status: "+this.i.i.friendlyName),o6(this,null)}if(a&&b){if(!this.i){c=K4(this.l.Ug(),a);if(!c){m6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){m6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=XLa(this,c);a||(m6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ma,(0,g.C)(function(d){this.Hd("Failed to set initial custom receivers: "+g.Cj(d))},this)));
m6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);o6(this,new k6(this.l,a),!0)}this.i.TB(b)}else m6("setConnectedScreenStatus: no screen.")};
g.k.pS=function(a){this.Ga()?this.Hd("Setting connection data on disposed cast v2"):this.i?this.i.tq(a):this.Hd("Setting connection data without a session")};
g.k.UL=function(){this.Ga()?this.Hd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),o6(this,null)):m6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.ZH,this),(0,g.C)(this.bR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.OD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=oLa,b=g.La("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.Ci(this.i);g.O.prototype.va.call(this)};
g.k.Hd=function(a){K5("Controller",a)};
g.k.bI=function(a,b){this.i==a&&(b||o6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.EQ=function(a,b){if(!this.Ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),m6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)m6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{m6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:o6(this,
new k6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:o6(this,new g6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:o6(this,new d6(this.l,a,this.B));break;default:this.Hd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Hd("Stopping receiver w/o session: "+a.friendlyName)}else this.Hd("onReceiverAction_ called without receiver.")};
g.k.uP=function(a){if(this.Ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Hd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return m6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);o6(this,new g6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,h6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=TLa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Lo(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=ULa(b,c)):a=ULa(b,c)):a=j6(b);return a};
g.k.ZH=function(a){if(!this.Ga()){m6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)m6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),o6(this,new d6(this.l,b,this.B),!0);else{this.Hd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=K4(this.l.Ug(),c.label);d&&F4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(m6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ci(this.i),this.i=new d6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.bI,this,this.i)),this.i.tq(null));this.i.SB(a)}}};
g.k.TL=function(){return this.i?this.i.ND():null};
g.k.bR=function(a){this.Ga()||(this.Hd("Failed to estabilish a session: "+g.Cj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&o6(this,null))};
g.k.IQ=function(a){m6("Receiver availability updated: "+a);if(!this.Ga()){var b=n6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;n6(this)!=b&&this.W("yt-remote-cast2-availability-change",n6(this))}};
g.k.OD=function(){this.Ga()||(this.u=YLa(this),m6("Updating custom receivers: "+g.Cj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ma,(0,g.C)(function(){this.Hd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",n6(this)))};
l6.prototype.setLaunchParams=l6.prototype.pS;l6.prototype.setConnectedScreenStatus=l6.prototype.oS;l6.prototype.stopSession=l6.prototype.UL;l6.prototype.getCastSession=l6.prototype.TL;l6.prototype.requestSession=l6.prototype.requestSession;l6.prototype.init=l6.prototype.init;l6.prototype.dispose=l6.prototype.dispose;var u6=[];g.k=z6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";A6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Cj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.lc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+B6(this):this.C};
g.k.clone=function(){return new z6(F6(this))};g.v(H6,g.O);g.k=H6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){J6(this)?(this.i?this.i.play(null,g.Ma,O6(this,"play")):N6(this,"play"),M6(this,1,D6(I6(this))),this.W("remotePlayerChange")):K6(this,this.play)};
g.k.pause=function(){J6(this)?(this.i?this.i.pause(null,g.Ma,O6(this,"pause")):N6(this,"pause"),M6(this,2,D6(I6(this))),this.W("remotePlayerChange")):K6(this,this.pause)};
g.k.seekTo=function(a){if(J6(this)){if(this.i){var b=I6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.lc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ma,O6(this,"seekTo",{newTime:a}))}else N6(this,"seekTo",{newTime:a});M6(this,3,a);this.W("remotePlayerChange")}else K6(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(J6(this)){this.i?this.i.stop(null,g.Ma,O6(this,"stopVideo")):N6(this,"stopVideo");var a=I6(this);a.index=-1;a.videoId="";A6(a);L6(this,a);this.W("remotePlayerChange")}else K6(this,this.stop)};
g.k.setVolume=function(a,b){if(J6(this)){var c=I6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){K5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Hd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){K5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Hd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);N6(this,"setVolume",e)}c.muted=b;c.volume=a;L6(this,c)}else K6(this,g.Ta(this.setVolume,a,b))};
g.k.PD=function(a,b){if(J6(this)){var c=I6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Cj(b.style),g.Zb(a,c.trackData));N6(this,"setSubtitlesTrack",a);L6(this,c)}else K6(this,g.Ta(this.PD,a,b))};
g.k.setAudioTrack=function(a,b){J6(this)?(b=b.getLanguageInfo().getId(),N6(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=I6(this),a.audioTrackId=b,L6(this,a)):K6(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=I6(this);c=c||0;var m={videoId:a,currentIndex:c};E6(l,a,c);void 0!==b&&(C6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Cj(h));N6(this,"setPlaylist",m);d||L6(this,l)};
g.k.Ow=function(a,b){if(J6(this)){if(a&&b){var c=I6(this);E6(c,a,b);L6(this,c)}N6(this,"previous")}else K6(this,g.Ta(this.Ow,a,b))};
g.k.nextVideo=function(a,b){if(J6(this)){if(a&&b){var c=I6(this);E6(c,a,b);L6(this,c)}N6(this,"next")}else K6(this,g.Ta(this.nextVideo,a,b))};
g.k.pF=function(){J6(this)?N6(this,"dismissAutoplay"):K6(this,this.pF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.O.prototype.dispose.call(this)};
g.k.va=function(){jMa(this);this.u=null;this.B.clear();G6(this,null);g.O.prototype.va.call(this)};
g.k.VB=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.kb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.BQ=function(a,b){this.W(a,b)};
g.k.gP=function(a){if(!a)this.gt(null),G6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=I6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,L6(this,b)}};
g.k.gt=function(a){K5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),kMa(this),this.W("remotePlayerChange")};
g.k.fP=function(a){a?(kMa(this),this.W("remotePlayerChange")):this.gt(null)};
g.k.oC=function(){N6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.nP=function(){var a=gMa();a&&G6(this,a)};
g.k.Hd=function(a){K5("CP",a)};g.v(P6,g.O);g.k=P6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ac.listId=c);this.ac.videoId=d;this.ac.index=h||0;this.ac.state=3;C6(this.ac,m);this.B="UNSUPPORTED";Q6("Connecting with setPlaylist and params: "+g.Cj(l));this.i.connect({method:"setPlaylist",
params:g.Cj(l)},a,jKa())}else Q6("Connecting without params"),this.i.connect({},a,jKa());mMa(this)};
g.k.fx=function(a){this.i.fx(a)};
g.k.dispose=function(){this.Ga()||(this.W("beforeDispose"),R6(this,3));g.O.prototype.dispose.call(this)};
g.k.va=function(){S6(this);U6(this);T6(this);g.hp(this.J);this.J=NaN;g.hp(this.L);this.L=NaN;this.u=null;g.Mp(this.V);this.V.length=0;this.i.dispose();g.O.prototype.va.call(this);this.B=this.G=this.l=this.ac=this.i=null};
g.k.vN=function(){this.Tp(2)};
g.k.kP=function(){Q6("Channel opened");this.ma&&(this.ma=!1,T6(this),this.Y=g.fp((0,g.C)(function(){Q6("Timing out waiting for a screen.");this.Tp(1)},this),15E3));
nKa(mLa(this.i),this.Ba)};
g.k.hP=function(){Q6("Channel closed");isNaN(this.C)?P4(!0):P4();this.dispose()};
g.k.iP=function(a,b){P4();isNaN(this.Ds())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),Q6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,Q6("Channel error: "+a+" with reconnection in "+this.Ds()+" ms"),R6(this,2))};
g.k.jP=function(a){a.params?Q6("Received: action="+a.action+", params="+g.Cj(a.params)):Q6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=Y4(a.params.devices);this.l=g.Qc(a,function(c){return new D4(c)});
a=!!g.fb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
pMa(this,a);break;case "loungeScreenDisconnected":g.pb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
pMa(this,!1);break;case "remoteConnected":var b=new D4(Y4(a.params.device));g.fb(this.l,function(c){return b?c.id==b.id:!1})||UJa(this.l,b);
break;case "remoteDisconnected":b=new D4(Y4(a.params.device));g.pb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":rMa(this,a);break;case "nowPlaying":tMa(this,a);break;case "onStateChange":sMa(this,a);break;case "onAdStateChange":uMa(this,a);break;case "onVolumeChanged":vMa(this,a);break;case "onSubtitlesTrackChanged":qMa(this,a);break;case "nowAutoplaying":wMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":xMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:Q6("Unrecognized action: "+a.action)}};
g.k.fS=function(){if(this.u){var a=this.u;this.u=null;this.ac.videoId!=a&&V6(this,"getNowPlaying")}};
g.k.qN=function(){var a=3;this.Ga()||(a=0,isNaN(this.Ds())?F5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Tp=function(a){Q6("Disconnecting with "+a);S6(this);this.W("beforeDisconnect",a);1==a&&P4();nLa(this.i,a);this.dispose()};
g.k.oN=function(){var a=this.ac;this.u&&(a=this.ac.clone(),E6(a,this.u,a.index));return F6(a)};
g.k.qS=function(a){var b=new z6(a);b.videoId&&b.videoId!=this.ac.videoId&&(this.u=b.videoId,g.hp(this.J),this.J=g.fp((0,g.C)(this.fS,this),5E3));var c=[];this.ac.listId==b.listId&&this.ac.videoId==b.videoId&&this.ac.index==b.index||c.push("remoteQueueChange");this.ac.playerState==b.playerState&&this.ac.volume==b.volume&&this.ac.muted==b.muted&&D6(this.ac)==D6(b)&&g.Cj(this.ac.trackData)==g.Cj(b.trackData)||c.push("remotePlayerChange");this.ac.reset(a);g.Db(c,function(d){this.W(d)},this)};
g.k.TF=function(){var a=this.i.G.id,b=g.fb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Ds=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Va():NaN};
g.k.mN=function(){return this.B||"UNSUPPORTED"};
g.k.nN=function(){return this.G||""};
g.k.VL=function(){if(!isNaN(this.Ds())){var a=this.i.l;a.i.xg();a.start()}};
g.k.nS=function(a,b){V6(this,a,b);oMa(this)};
g.k.QD=function(){var a=g.wo("SID","")||"",b=g.wo("SAPISID","")||"",c=g.wo("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.rf(g.Ve(a),2);b=g.rf(g.Ve(b),2);c=g.rf(g.Ve(c),2);return g.rf(g.Ve(a+","+b+","+c),2)};
P6.prototype.subscribe=P6.prototype.subscribe;P6.prototype.unsubscribeByKey=P6.prototype.Mf;P6.prototype.getProxyState=P6.prototype.qN;P6.prototype.disconnect=P6.prototype.Tp;P6.prototype.getPlayerContextData=P6.prototype.oN;P6.prototype.setPlayerContextData=P6.prototype.qS;P6.prototype.getOtherConnectedRemoteId=P6.prototype.TF;P6.prototype.getReconnectTimeout=P6.prototype.Ds;P6.prototype.getAutoplayMode=P6.prototype.mN;P6.prototype.getAutoplayVideoId=P6.prototype.nN;P6.prototype.reconnect=P6.prototype.VL;
P6.prototype.sendMessage=P6.prototype.nS;P6.prototype.getXsrfToken=P6.prototype.QD;g.v(W6,O5);g.k=W6.prototype;g.k.Ug=function(a){return this.Ef.$_gs(a)};
g.k.contains=function(a){return!!this.Ef.$_c(a)};
g.k.get=function(a){return this.Ef.$_g(a)};
g.k.start=function(){this.Ef.$_st()};
g.k.add=function(a,b,c){this.Ef.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ef.$_r(a,b,c)};
g.k.Cx=function(a,b,c,d){this.Ef.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ef.$_ubk(this.i[a]);this.i.length=0;this.Ef=null;O5.prototype.va.call(this)};
g.k.WL=function(){this.W("screenChange")};
g.k.iQ=function(){this.W("onlineScreenChange")};
Y5.prototype.$_st=Y5.prototype.start;Y5.prototype.$_gspc=Y5.prototype.QL;Y5.prototype.$_gsppc=Y5.prototype.MD;Y5.prototype.$_c=Y5.prototype.contains;Y5.prototype.$_g=Y5.prototype.get;Y5.prototype.$_a=Y5.prototype.add;Y5.prototype.$_un=Y5.prototype.Cx;Y5.prototype.$_r=Y5.prototype.remove;Y5.prototype.$_gs=Y5.prototype.Ug;Y5.prototype.$_gos=Y5.prototype.LD;Y5.prototype.$_s=Y5.prototype.subscribe;Y5.prototype.$_ubk=Y5.prototype.Mf;var i7=null,o7=!1,X6=null,Y6=null,n7=null,b7=[];g.v(p7,g.F);g.k=p7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Qb;a.unsubscribe("proxyStateChange",this.XH,this);a.unsubscribe("remotePlayerChange",this.qt,this);a.unsubscribe("remoteQueueChange",this.Lw,this);a.unsubscribe("previousNextChange",this.UH,this);a.unsubscribe("nowAutoplaying",this.OH,this);a.unsubscribe("autoplayDismissed",this.lH,this);this.Qb=this.l=null};
g.k.RD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Qb.eb)if(q7(this)){if(!I6(this.Qb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":I6(this.Qb).lc()?this.Qb.pause():this.Qb.play();break;case "control_play":this.Qb.play();break;case "control_pause":this.Qb.pause();break;case "control_seek":this.J.xg(c[0],c[1]);break;case "control_subtitles_set_track":r7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();s7(this,0===c?void 0:c);break;case "control_seek":s7(this,c[0]);break;case "control_subtitles_set_track":r7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.dP=function(a){this.L.xg(a)};
g.k.US=function(a){this.RD("control_subtitles_set_track",g.Sb(a)?null:a)};
g.k.iJ=function(){var a=this.I.getOption("captions","track");g.Sb(a)||r7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.RP=function(){g.Sb(this.B)||IMa(this,this.B);this.C=!1};
g.k.XH=function(a,b){this.u.stop();2===b&&this.dJ()};
g.k.qt=function(){if(q7(this)){this.i.stop();var a=I6(this.Qb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Oe=1;break;case 1082:case 1083:this.l.Oe=0;break;default:this.l.Oe=-1}switch(a.playerState){case 1081:case 1:this.Hb(new g.TI(8));this.cJ();break;case 1085:case 3:this.Hb(new g.TI(9));break;case 1083:case 0:this.Hb(new g.TI(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Hb(new g.TI(4));break;case 2:this.Hb(new g.TI(4));this.Tb(D6(a));
break;case -1:this.Hb(new g.TI(64));break;case -1E3:this.Hb(new g.TI(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=I6(this.Qb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,IMa(this,a));a=I6(this.Qb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.DJ()}else HMa(this)};
g.k.UH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Lw=function(){q7(this)||HMa(this)};
g.k.OH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.lH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){q7(this)&&this.Qb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===I6(this.Qb).playerState?s7(this,a):b&&this.Qb.seekTo(a)};
g.k.DJ=function(){var a=this;if(q7(this)){var b=I6(this.Qb);this.events.dc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){GMa(a,c)})}};
g.k.cJ=function(){this.i.stop();if(!this.Qb.Ga()){var a=I6(this.Qb);a.lc()&&this.Hb(new g.TI(8));this.Tb(D6(a));this.i.start()}};
g.k.dJ=function(){this.u.stop();this.i.stop();var a=this.Qb.u.getReconnectTimeout();2==this.Qb.eb&&!isNaN(a)&&this.u.start()};
g.k.Hb=function(a){this.u.stop();var b=this.G;if(!g.YI(b,a)){var c=g.V(a,2);c!==g.V(this.G,2)&&this.I.Mo(c);this.G=a;KMa(this.l,b,a)}};g.v(t7,g.W);t7.prototype.Pc=function(){this.i.show()};
t7.prototype.zb=function(){this.i.hide()};
t7.prototype.l=function(){g.zI("https://support.google.com/youtube/answer/7640706")};
t7.prototype.u=function(){C4("mdx-manual-pairing-popup-ok");this.zb()};g.v(u7,g.W);u7.prototype.Pc=function(){this.i.show()};
u7.prototype.zb=function(){this.i.hide()};
u7.prototype.l=function(){C4("mdx-privacy-popup-cancel");this.zb()};
u7.prototype.u=function(){C4("mdx-privacy-popup-confirm");this.zb()};g.v(v7,g.W);v7.prototype.l=function(a){JMa(this,a.state)};g.v(w7,g.LO);w7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Cm=g.Eb(a,this.i,this),g.MO(this,g.Qc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.jh(a),this.enable(!0)):this.enable(!1)};
w7.prototype.i=function(a){return a.key};
w7.prototype.di=function(a){return"cast-selector-receiver"===a?"Cast...":this.Cm[a].name};
w7.prototype.We=function(a){g.LO.prototype.We.call(this,a);this.I.setOption("remote","currentReceiver",this.Cm[a]);this.wb.zb()};g.v(x7,g.$L);g.k=x7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.dD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};BMa(b,a);this.subscriptions.push(g.Lq("yt-remote-before-disconnect",this.cP,this));this.subscriptions.push(g.Lq("yt-remote-connection-change",this.JQ,this));this.subscriptions.push(g.Lq("yt-remote-receiver-availability-change",
this.WH,this));this.subscriptions.push(g.Lq("yt-remote-auto-connect",this.GQ,this));this.subscriptions.push(g.Lq("yt-remote-receiver-resumed",this.FQ,this));this.subscriptions.push(g.Lq("mdx-privacy-popup-confirm",this.XR,this));this.subscriptions.push(g.Lq("mdx-privacy-popup-cancel",this.WR,this));this.subscriptions.push(g.Lq("mdx-manual-pairing-popup-ok",this.nO,this));this.WH()};
g.k.load=function(){this.player.cancelPlayback();g.$L.prototype.load.call(this);this.nh=new p7(this,this.player,this.Qb);var a=(a=FMa())?a.currentTime:0;var b=m7()?new H6(g7(),void 0):null;0==a&&b&&(a=D6(I6(b)));0!==a&&this.Tb(a);KMa(this,this.Yc,this.Yc);this.player.Sj(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Jl=this.Di;g.Di(this.nh,this.Qb);this.Qb=this.nh=null;g.$L.prototype.unload.call(this);this.player.Sj(5);y7(this)};
g.k.va=function(){g.Mq(this.subscriptions);g.$L.prototype.va.call(this)};
g.k.Nj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.nh.RD.apply(this.nh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Oe};
g.k.rN=function(){return this.loaded?this.nh.suggestion:null};
g.k.Cj=function(){return this.Qb?I6(this.Qb).Cj:!1};
g.k.hasNext=function(){return this.Qb?I6(this.Qb).hasNext:!1};
g.k.Tb=function(a,b){this.GG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.GG};
g.k.getProgressState=function(){var a=I6(this.Qb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ne():!a.isAdPlaying()&&this.player.Ne(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+B6(a):a.u,isAtLiveHead:1>=(a.l?a.i+B6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+B6(a):a.i,seekableStart:0<a.B?a.B+
B6(a):a.B}};
g.k.nextVideo=function(){this.Qb&&this.Qb.nextVideo()};
g.k.Ow=function(){this.Qb&&this.Qb.Ow()};
g.k.cP=function(a){1===a&&(this.xB=this.Qb?I6(this.Qb):null)};
g.k.JQ=function(){var a=m7()?new H6(g7(),void 0):null;if(a){var b=this.Jl;this.loaded&&this.unload();this.Qb=a;this.xB=null;b.key!==this.Di.key&&(this.Jl=b,this.load())}else g.Ci(this.Qb),this.Qb=null,this.loaded&&(this.unload(),(a=this.xB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,D6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.WH=function(){var a=[this.Di],b=a.concat,c=CMa();v6()&&g.Tu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Cm=b.call(a,c);a=h7()||this.Di;z7(this,a);this.player.La("onMdxReceiversChange")};
g.k.GQ=function(){var a=h7();z7(this,a)};
g.k.FQ=function(){this.Jl=h7()};
g.k.XR=function(){this.xt=!0;y7(this);o7=!1;i7&&k7(i7,1);i7=null};
g.k.WR=function(){this.xt=!1;y7(this);z7(this,this.Di);this.Jl=this.Di;o7=!1;i7=null;this.player.playVideo()};
g.k.nO=function(){this.lw=!0;y7(this);g.Su("yt-remote-manual-pairing-warning-shown",!0,2592E3);o7=!1;i7&&k7(i7,1);i7=null};
g.k.Je=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Cm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?x6():z7(this,b)),this.loaded?this.Jl:this.Di;case "quickCast":return 2===this.Cm.length&&"cast-selector-receiver"===this.Cm[1].key?(b&&x6(),!0):!1}};
g.k.oC=function(){this.Qb.oC()};
g.k.Sh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.fM.remote=x7;})(_yt_player);
